name: Build, Pack, and Publish Pre-Release

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/core/sdk
    name: Build, Pack, and Publish Pre-Release
    steps:
    - uses: actions/checkout@v2
        
    - name: Install gitversion
      run: | 
        dotnet tool install -g GitVersion.Tool
        cat << \EOF >> ~/.bash_profile
        # Add .NET Core SDK tools
        export PATH="$PATH:/github/home/.dotnet/tools"
        EOF
      
    - name: Run gitversion with dotnet
      if: success()
      run: dotnet-gitversion /l console /output buildserver /updateAssemblyInfo
        
    - name: Build with dotnet
      if: success()
      run: dotnet build -c Release
      
    - name: Test with dotnet
      if: success()
      run: dotnet test -c Release --no-build
      
    - name: Package with dotnet
      if: success()
      run: dotnet pack -c Release --no-build --include-source --include-symbols
      
    - name: Push to MyGet with dotnet
      if: success()
      run: dotnet nuget push *.nupkg -s https://www.myget.org/F/tomsoliver/auth/67194d00-4c6f-402b-af6b-55a739d55c89/api/v3/index.json
